services:
  postgres:
    image: postgres:latest
    ports:
      - 5439:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=cache-secret
      - POSTGRES_USER=cache-demo
      - POSTGRES_DB=spring-cache